apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sui-trace.fullname" . }}-secrets
type: Opaque
stringData:
  databaseUrl: {{ .Values.externalSecrets.databaseUrl | quote }}
  redisUrl: {{ .Values.externalSecrets.redisUrl | quote }}
  jwtSecret: {{ .Values.externalSecrets.jwtSecret | quote }}
  telegramBotToken: {{ .Values.externalSecrets.telegramBotToken | quote }}
  resendApiKey: {{ .Values.externalSecrets.resendApiKey | quote }}
